pull_request_rules:
  - name: automatic merge dependabot pull requests on master
    conditions:
      - author=dependabot[bot]
      - label~=dependencies
      - status-success~=Travis CI
      - status-success~=WIP
      - status-success~=codecov/project
    actions:
      merge:
        method: merge
        strict: true
  - name: automatic merge on CI success and review
    conditions:
      - label~=merge pull
      - status-success~=Travis CI
      - status-success~=WIP
      - status-success~=codecov/project
    actions:
      merge:
        method: merge
        strict: true
  - name: delete merged branch
    conditions:
      - merged
    actions:
      delete_head_branch: {}