language: node_js
branches:
  only:
    - master
node_js:
  - "8"
  - "10"
  - "lts/*"
  - "node"
install:
  - npm ci
script:
  - npm run lint:ci
  - npm run test
  - npx codecov
  - npm run build
cache:
  directories:
    - node_modules
