language: node_js
branches:
  only:
    - master
node_js:
  - "10"
  - "12"
  - "lts/*"
  - "node"
install:
  - npm ci
script:
  - npm run test
  - npx codecov
cache:
  directories:
    - node_modules
